#SPDX-License-Identifier: MIT-0
---
- name: Validate ansible user variables
  ansible.builtin.assert:
    that:
      - security_ansible_user_name | length > 0
      - security_ansible_user_ssh_key | length > 0
    fail_msg: "You should set security_ansible_user_name and security_ansible_user_ssh_key variables in group_vars or host_vars"
    quiet: true
  when: security_manage_ansible_user | bool

- name: Validate admin user variables
  ansible.builtin.assert:
    that:
      - security_admin_user_name | length > 0
      - security_admin_user_ssh_key | length > 0
    fail_msg: "You should set security_admin_user_name and security_admin_user_ssh_key variables in group_vars or host_vars"
    quiet: true
  when: security_manage_admin_user | bool

- name: Validate admin password when sudo mode is not nopasswd
  ansible.builtin.assert:
    that:
      - security_admin_user_password | length > 0
    fail_msg: "You should set security_admin_user_password variable in group_vars or host_vars when security_admin_user_sudo_mode is not nopasswd"
    quiet: true
  when:
    - security_manage_admin_user | bool 
    - security_admin_user_sudo_mode != "nopasswd"

- name: Update & upgrade
  ansible.builtin.apt:
    update_cache: "{{ security_apt_update_cache }}"
    upgrade: "{{ security_apt_upgrade }}"
    cache_valid_time: "{{ security_apt_cache_valid_time }}"

- name: Remove unused dependencies
  ansible.builtin.apt:
    autoremove: "{{ security_apt_autoremove }}"
    purge: "{{ security_apt_purge }}"

- name: Manage ansible service user
  when: security_manage_ansible_user | bool
  block:
    - name: Create ansible service user
      ansible.builtin.user:
        name: "{{ security_ansible_user_name }}"
        shell: "{{ security_ansible_user_shell }}"
        create_home: true
        state: present
        password: "!" # убираем пароль для пользователя. remove password for user

    - name: Deploy ansible user ssh key
      ansible.posix.authorized_key:
        user: "{{ security_ansible_user_name }}"
        key: "{{ security_ansible_user_ssh_key }}"
        state: present
        exclusive: false # не трогаем остальные ключи, которые могут быть в файле authorized_keys. don't touch other keys in authorized_keys

    - name: Grant passwordless sudo to ansible user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/50-{{ security_ansible_user_name }}"
        content: "{{ security_ansible_user_name }} ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'

- name: Manage admin user
  when: security_manage_admin_user | bool
  block:
    - name: Create admin user
      ansible.builtin.user:
        name: "{{ security_admin_user_name }}"
        shell: "{{ security_admin_user_shell }}"
        groups: "{{ security_admin_user_groups }}"
        append: true
        create_home: true
        state: present
        password: "{{ security_admin_user_password if security_admin_user_sudo_mode != 'nopasswd' else omit }}" # могли бы убрать пароль через "!" но тогда снесем пароль, если пользователь уже существует
      no_log: true 

    - name: Deploy admin user ssh key
      ansible.posix.authorized_key:
        user: "{{ security_admin_user_name}}"
        key: "{{ security_admin_user_ssh_key }}"
        state: present
        exclusive: false # не трогаем остальные ключи, которые могут быть в authorized_keys. dont touch other keys in authorized_keys

    - name: Grant passwordless sudo to admin user when nopasswd mode
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/50-{{ security_admin_user_name }}"
        content: "{{ security_admin_user_name }} ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'
      when: security_admin_user_sudo_mode == "nopasswd"

    - name: Remove admin passwordless sudo when its required
      ansible.builtin.file:
        path: "/etc/sudoers.d/50-{{ security_admin_user_name }}"
        state: absent
      when: security_admin_user_sudo_mode != "nopasswd"

- name: Start and Enable ssh.service
  ansible.builtin.systemd: 
    name: ssh.service
    state: started
    enabled: true

# Disabling ssh.socket to avoid conflicts with ssh.service (Tested on Yandex Cloud Ubuntu 22.04 LTS. Ssh.service and ssh.socket has conflict section in systemd. If you starting one service, another will be dead) 

- name: Check if ssh.socket exists
  ansible.builtin.command:
    cmd: systemctl list-unit-files ssh.socket
  register: ssh_socket_unit
  changed_when: false
  failed_when: false

- name: Stop and Disable ssh.socket
  ansible.builtin.systemd: 
    name: ssh.socket
    state: stopped
    enabled: false
  when:
    - "'ssh.socket' in ssh_socket_unit.stdout"

- name: Build ssh allowed users list
  ansible.builtin.set_fact:
    security_ssh_allow_users_effective: >-
      {{ (
      ([security_ansible_user_name] if security_manage_ansible_user | bool else [])
      + ([security_admin_user_name] if security_manage_admin_user | bool else [])
      + security_ssh_allow_users
      ) | unique | join(' ') }}

- name: Ensure current connection user is in allowed users list
  ansible.builtin.assert:
    that:
      - ansible_user in security_ssh_allow_users_effective.split(' ')
    fail_msg: "Current connection user {{ ansible_user }} is not in allowed users list. Add it to security_ssh_allow_users variable in group_vars or host_vars"
    quiet: true
  when: security_ssh_allow_users_effective | length > 0 # If security_ssh_allow_users_effective is empty, then we allow all users, so no need to check current connection user

- name: Deploy sshd configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/00-hardening.conf
    owner: root
    group: root
    mode: '0644'
    validate: '/usr/sbin/sshd -t -f %s'
  notify:
    - Restart sshd

- name: Validate sshd configuration
  ansible.builtin.command:
    cmd: /usr/sbin/sshd -t
  changed_when: false
# tasks file for security

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Reset ufw to default #always changed
  community.general.ufw:
    state: reset
  when: security_ufw_reset | bool

- name: Set default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - {direction: incoming, policy: "{{ security_ufw_policy_incoming }}"}
    - {direction: outgoing, policy: "{{ security_ufw_policy_outgoing }}"}
  loop_control:
    label: "{{ item.direction }}: {{ item.policy }}"

- name: Allow SSH port
  community.general.ufw:
    rule: allow
    port: "{{ security_ssh_port}}"
    proto: tcp

- name: Allow configured ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ security_ufw_allowed_ports }}"
  loop_control: # for better logging in output
    label: "{{ item.port }}/{{ item.proto | default('tcp') }}"

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Install python3-pyinotify dependency for fail2ban
  ansible.builtin.apt:
    name: python3-pyinotify
    state: present
  when: security_fail2ban_sshd_backend == "pyinotify"

- name: Deploy fail2ban configuration for sshd
  ansible.builtin.template:
    src: sshd_jail.j2
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart fail2ban

- name: Validate fail2ban configuration # fail2ban has no way to check a single file, so we check the whole configuration here.
  ansible.builtin.command:
    cmd: fail2ban-client -t
  changed_when: false

- name: Enable fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true