#SPDX-License-Identifier: MIT-0
---
- name: Preflight tasks
  ansible.builtin.import_tasks: preflight.yml
  tags: [always]

- name: Apt tasks
  ansible.builtin.import_tasks: apt.yml
  tags: [apt]

- name: Users tasks
  ansible.builtin.import_tasks: users.yml
  tags: [users]

- name: SSH tasks
  ansible.builtin.import_tasks: ssh.yml
  tags: [ssh]

- name: Ufw tasks
  ansible.builtin.import_tasks: ufw.yml
  tags: [ufw]

- name: Fail2ban tasks
  ansible.builtin.import_tasks: fail2ban.yml
  tags: [fail2ban]