security_ansible_user_name: ansible
security_ansible_user_ssh_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
security_admin_user_name: admin
security_admin_user_ssh_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

security_ufw_allowed_ports:
  - { port: 80, proto: tcp, comment: "http" }
  - { port: 443, proto: tcp, comment: "https" }
  # - { port: 9100, proto: tcp, from_ip: "203.0.113.10", comment: "node_exporter" }